from tkinter import*
window=Tk()
window.geometry("443x540")
window.title("google Form")
def values():
    print(uservalue.get())
    print(passvalue.get())
    print(agevalue.get())
User=Label(window,text="username")
Passaword=Label(window,text="password")
age=Label(window,text="Age")
User.grid()
Passaword.grid()
age.grid()
uservalue=StringVar()#variable classes
passvalue=StringVar()
agevalue=IntVar()
name=Entry(window,textvariable=uservalue)
pass_word=Entry(window,textvariable=passvalue)
age_val=Entry(window,textvariable=agevalue)
name.grid(row=0,column=1)
pass_word.grid(row=1,column=1)
age_val.grid(row=2,column=1)
B1=Button(window,text="Sumbit",command=values)
B1.grid(row=3,column=0)
window.mainloop()